import { SxProps, Theme } from '@mui/material';

export const countryCardStyles: Record<string, SxProps<Theme>> = {
  card: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    background: 'linear-gradient(135deg, rgba(255,255,255,0.95) 0%, rgba(255,255,255,0.9) 100%)',
    backdropFilter: 'blur(20px)',
    border: '1px solid rgba(255, 255, 255, 0.5)',
    borderRadius: 4,
    overflow: 'hidden',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'pointer',
    position: 'relative',
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 4,
      padding: '1px',
      background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.1) 0%, rgba(139, 92, 246, 0.1) 100%)',
      WebkitMask: 'linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)',
      WebkitMaskComposite: 'xor',
      maskComposite: 'exclude',
      opacity: 0,
      transition: 'opacity 0.3s ease',
    },
    '&:hover': {
      transform: 'translateY(-8px) scale(1.02)',
      boxShadow: '0 20px 40px rgba(99, 102, 241, 0.15), 0 8px 16px rgba(0, 0, 0, 0.1)',
      '&::before': {
        opacity: 1,
      },
    },
  },
  flagContainer: {
    position: 'relative',
    overflow: 'hidden',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  flag: {
    objectFit: 'cover',
    transition: 'transform 0.5s cubic-bezier(0.4, 0, 0.2, 1)',
    width: '100%',
    '&:hover': {
      transform: 'scale(1.1)',
    },
  },
  flagVisible: {
    position: 'relative',
    zIndex: 0,
  },
  flagOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'linear-gradient(to bottom, transparent 0%, rgba(0, 0, 0, 0.1) 100%)',
    pointerEvents: 'none',
    zIndex: 1,
  },
  skeleton: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    bgcolor: 'rgba(99, 102, 241, 0.1)',
    zIndex: 0,
  },
  flagPlaceholder: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.2) 0%, rgba(139, 92, 246, 0.2) 100%)',
    zIndex: 0,
  },
  flagPlaceholderText: {
    fontWeight: 700,
    color: 'primary.main',
    fontSize: '1.5rem',
    letterSpacing: '0.1em',
  },
  content: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    p: 2.5,
    pb: 2.5,
  },
  name: {
    mb: 2,
    fontWeight: 700,
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
    fontSize: '1.25rem',
    letterSpacing: '-0.02em',
  },
  details: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    mt: 'auto',
  },
  detailItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 1,
    p: 1,
    borderRadius: 2,
    background: 'rgba(99, 102, 241, 0.05)',
    transition: 'all 0.2s ease',
    '&:hover': {
      background: 'rgba(99, 102, 241, 0.1)',
      transform: 'translateX(4px)',
    },
  },
  icon: {
    color: 'primary.main',
    fontSize: '1.25rem',
    mt: 0.25,
    flexShrink: 0,
  },
  label: {
    display: 'block',
    color: 'text.secondary',
    fontWeight: 500,
    fontSize: '0.7rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    mb: 0.25,
  },
  value: {
    color: 'text.primary',
    fontWeight: 600,
    fontSize: '0.875rem',
    lineHeight: 1.4,
  },
};

